### PR TITLE
Added support for Select field type.

### PR DESCRIPTION
**Pull request by ymauray**
I'm working on a couple of plugins, and they will require a new type of field in the UI : Select (same as text-align, but configurable from the plugin).
Thanks.

### CODE REVIEW

**Comment by ymauray** [comment]
Corresponding PR for the UI : https://github.com/unix-streamdeck/streamdeckui/pull/16

**Comment by The-Jonsey** [comment]
as it happens I was working on something similar for a large-ish feature I'm working on... I'll get this merged though as you've already done the UI for it too, I'll get a release on this sorted when I merge, then could you update the mod file on the UI to use the new released version?

**Comment by ymauray** [comment]
Sure !

**Comment by The-Jonsey** [comment]
cool, v1.0.1 has been released

**Pull request merged**
